"use client";
import react from "react";
import Header from "@/components/ui/features/Header/Header";
import Main from "@/components/ui/element/Main/Main";
import GoToTopButton from "../components/ui/element/GoToTopButton/GoToTopButton";
import Head from "next/head";
import ChatBot from "@/components/ui/features/MessengerChatbot/MessengerChatbot";

export default function Home() {
  return (
    <>
      <Head>
        <title>Rakib Khan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main />
      <GoToTopButton />
      <ChatBot/>
    </>
  );
}
