export const CHANGE_REGISTER_INPUT = 'CHANGE_REGISTER_INPUT';
export const REGISTER_STEP_INCREMENT_DECREMENT = "REGISTER_STEP_INCREMENT_DECREMENT"
export const CHANGE_SUBMIT_STATUS = 'CHANGE_SUBMIT_STATUS'
export const UPDATE_AUTHENTICATION_ERROR = 'UPDATE_AUTHENTICATION_ERROR'
export const CHANGE_LOGIN_INPUT = 'CHANGE_LOGIN_INPUT'