export const GET_REQUEST_LIST = "GET_REQUEST_LIST";
export const CONFIRM_PAYLOAD = "CONFIRM_PAYLOAD";
export const SEND_OTP_REQUEST = "SEND_OTP_REQUEST";
export const CONFIRM_SHIPPING = "CONFIRM_SHIPPING";